Тренажер по модулю 3
Матрицы и векторы

In [5]:
import numpy as np
from math import sqrt 
from numpy.linalg import inv
from numpy.polynomial.polynomial import Polynomial as P

Задача 1
Даны n точек на плоскости найти центр и минимальный радиус круга, куда попадут все эти точки.

In [22]:
n = int(input()) # Число точек
A = []
for i in range(n):
    line = np.array(input().split(), dtype = float)
    A.append(line)
A = np.array(A)
# print(A)
center = np.mean(A, axis = 0)
print("центр в точке (%6.3f, %6.3f)" % (center[0], center[1]))
#print("центр в точке (%6.3f, %6.3f)" % center)
#x = A[:, 0]
#x_center = np.mean(x)

#y = A[:, 0]
#y_center= np.mean(y)

R = A - center
r_list = []
for i in range(n):
    x = R[0, 0] 
    y = R[0, 1]
    r = sqrt(x ** 2 + y ** 2)
    r_list.append(r)
    R = np.delete(R, 0, 0)
    print(R)
#print(r_list)
r_list = np.array(r_list)    
radius = r_list.max()

print("центр в точке (%6.3f, %6.3f), r = %6.3f" %(center[0], center[1], radius))

4
13.5 -5.7
17.8 -17.6
-8.1 16.9
10.6 14.9
[[ 13.5  -5.7]
 [ 17.8 -17.6]
 [ -8.1  16.9]
 [ 10.6  14.9]]
центр в точке ( 8.450,  2.125)
[[  9.35  -19.725]
 [-16.55   14.775]
 [  2.15   12.775]]
[[-16.55   14.775]
 [  2.15   12.775]]
[[ 2.15  12.775]]
[]
r = 22.186


Задача 2 


Задача
Электрическая цепь состоит из n ветвей, каждая ветвь состоит из резистора и источника ЭДС включенных последовательно. Известны сопротивление резистора r каждой ветви  и сила тока в каждой ветви i.

In [5]:
r = np.array(input().split(), dtype = float) # Список со значением сопротивления на каждом резисторе
I = np.array(input().split(), dtype = float) # Список со значением силы тока на каждом резисторе
R_reverce = 0
I_chain = 0
if len(r) == len(I):
    for i in range(len(r)):
        R_reverce = R_reverce + 1/r[i]
        I_chain = I_chain + I[i]
    R = 1 / R_reverce 
    U = I_chain * R
    print("R = %6.3f Ом, I = %6.3f А, U = %6.3f В" % (R, I_chain, U))
else:
    print('Error. Wrong lenght of arrays')


0.9 0.6 1.3 1.6 1.6 0.9 0.9 1.4 1.5 0.6
4.1 3.7 2.9 2.8 2.9 2.6 4.2 3.2 2.8 2.8
R =  0.099 Ом, I = 32.000 А, U =  3.179 В


Красивое и простое решение

In [6]:
import numpy as np

R = 1 / ((1 / np.array(input().split(), dtype = float)).sum())
I = np.array(input().split(), dtype = float).sum()

print("R = %6.3f Ом, I = %6.3f А, U = %6.3f В" % (R, I, R * I))

0.9 0.6 1.3 1.6 1.6 0.9 0.9 1.4 1.5 0.6
4.1 3.7 2.9 2.8 2.9 2.6 4.2 3.2 2.8 2.8
R =  0.099 Ом, I = 32.000 А, U =  3.179 В


Задача 3

Измерили дальности полета воды, выпущенной из шланга, под разными углами к горизонту. По этим данным построить тренд (полином второй степени) зависимости дальности полета от угла наклона шланга и найти дальность полета струи воды для произвольного угла.

In [9]:
angle_of_hose = np.array(input().split(), dtype = int)
lenght_of_flow = np.array(input().split(), dtype = float)
angle_counted = float(input())

def get_trend(x, a):
    y = a[0] * x ** 2 + a[1] * x + a[2]
    return y

a = np.polyfit(angle_of_hose, lenght_of_flow, 2)
lenght_counted = get_trend(angle_counted, a)

print("Дальность: %6.2f м" % lenght_counted)


27 34 41 48 55 62 69 76 83 90 97
75.23 95.49 98.03 89.5 84.57 82.07 69.58 48.82 26.36 0.0 -26.12
34
Дальность:  89.19 м


In [ ]:
27 34 41 48 55 62 69 76 83 90 97
75.23 95.49 98.03 89.5 84.57 82.07 69.58 48.82 26.36 0.0 -26.12
34

Задача 4

Трое сотрудников получили премию в размере 2970 р., причем второй получил 1/3 того, что получил первый, и еще 180 р., а третий получил 1/3 денег второго и еще 130 р. Какую премию получил каждый?


In [14]:
A = np.array([[1, 1, 1], [-1/3, 1, 0], [0, -1/3, 1]])
B = np.array([[2970], [180], [130]])
#print(A)
#print(B)
x = np.dot(inv(A), B)
print("%4.0f р., %4.0f р., %4.0f р." % (x[0], x[1], x[2]))

1800 р.,  780 р.,  390 р.
